# Generated by Django 5.2.14 on 2026-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_sales_module_and_specialized_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño'), ('admin', 'Administrador'), ('cashier', 'Cajero'), ('inventory', 'Inventario'), ('credit_manager', 'Créditos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('paid', 'Pagada'), ('credit', 'Crédito'), ('cancelled', 'Cancelada')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('credit', 'Crédito')], max_length=20),
        ),
    ]
