# Generated by Django 5.2.14 on 2026-05-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_businessmembership_role_alter_sale_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='has_manual_price_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='original_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_override_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
