# Generated by Django 5.2.14 on 2026-05-25 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_saleitem_has_manual_price_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('sale_payment', 'Venta'), ('credit_payment', 'Abono de crédito'), ('refund', 'Reembolso'), ('manual_in', 'Entrada manual'), ('manual_out', 'Salida manual')], max_length=24)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('credit', 'Crédito')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_out_of_session', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='request_nonce',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='erp.cashsession'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='tendered_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('paid', 'Pagada'), ('credit', 'Pendiente de pago'), ('cancelled', 'Cancelada')], default='paid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['business', 'cash_session', 'created_at'], name='erp_salepay_busines_d1f06a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('request_nonce', ''), _negated=True), fields=('business', 'request_nonce'), name='unique_sale_nonce_per_business'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='erp.business'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='erp.cashsession'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='credit_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='erp.credittransaction'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='erp.sale'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='sale_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='erp.salepayment'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['business', 'cash_session', 'created_at'], name='erp_cashmov_busines_e642cd_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['business', 'movement_type', 'created_at'], name='erp_cashmov_busines_ed937f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['business', 'is_out_of_session', 'created_at'], name='erp_cashmov_busines_da5b81_idx'),
        ),
    ]
