# Generated by Django 5.2.14 on 2026-05-25 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_user_security_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserSecurity = apps.get_model("erp", "UserSecurity")
    db_alias = schema_editor.connection.alias

    for user in User.objects.using(db_alias).all():
        UserSecurity.objects.using(db_alias).get_or_create(user_id=user.id)


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_cashmovement_sale_request_nonce_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('password_expired_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_user_security_profiles, migrations.RunPython.noop),
    ]
